# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5680e2fce5e652eb344c54903cabcdb3c5a3a674d993d37a548f588ebdda469583fa634f0996ca8afcadf964ecc7964aa28b7734e2fb8d576a88a114bc41b7bb

test:
  secret_key_base: edff7e578327e742de8264ca07c639100e2ad7ca0b37b1f3462ecb60b68c68c2abbe8ba19faa7e9370ec68aa89313d4cd8254a768c34d9982a859c5a56d02f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
